# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

jobs:
  build:

    macos:
      xcode: 12.3.0 # Specify the Xcode version to use

    steps:
      - checkout
      - run: fastlane scan # Run tests using Fastlane
