# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    setup_circle_ci
    import_certificate(
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      certificate_path: 'DistributionCertificate.p12',
      certificate_password: ENV["CertificatePassword"] || "default"
    )
  end

  desc "Deploy beta build"
   lane :deployBeta do |options|
    gym(scheme: "Natofy", export_method: "app-store", configuration: "Release", clean: true, output_directory: "build")
    api_key = app_store_connect_api_key(key_id: ENV["KeyID"],issuer_id: ENV["IssuerID"],key_filepath: "~/Desktop/DecodedFiles/APIKeyFile.p8")
    testflight(ipa: "build/Natofy.ipa", skip_waiting_for_build_processing: true, api_key: api_key)
  end

   desc "Collect screenshots"
   lane :screenshots do |options|
   	sh "bash ../scripts/collect-screenshots.sh"
   end
end