name: Tag Latest Beta

# on:
#  schedule:
#    - cron: '25 22 * * *' # run at 10:22PM UTC

on:
  schedule:
    - cron: '05 19 * * *' # run at 10AM UTC
    # workflow_dispatch: # adding the workflow_dispatch so it can be triggered manually

jobs:
  Tag-Latest-Beta:
    runs-on: macOS-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Get tags
        run: git fetch --tags origin
      - name: Checkout and pull latest
        run: |
            git checkout master
            git pull origin master
      - name: Move latest_beta tag
        run: |
          LATESTBETATAG='latest_beta'
          LASTBETASHA=$(git rev-parse $LATESTBETATAG)
          CURRENTSHA=$(git rev-parse HEAD) #origin/master?
          echo "${LASTBETASHA}"
          echo "${CURRENTSHA}"
          if [ ${LASTBETASHA} != ${CURRENTSHA} ]; then
            echo "New commit on master. Moving latest_beta tag."
            echo "Deleting old tag and pushing"
            git tag -d ${LATESTBETATAG}
            git push origin :refs/tags/${LATESTBETATAG}
            echo "Creating new tag and pushing"
            git tag ${LATESTBETATAG}
            git push --tags
          else
            echo "No new commits determined. Exiting."
          fi
      - run: echo "This job's status is ${{ job.status }}."
